<?xml version="1.0"?>
<package format="3">
  <name>log_view</name>
  <version>0.3.0</version>
  <description>
    The log_view package provides a ncurses based terminal GUI for
    viewing and filtering log messages from podman containers via journalctl.

    This is an alternative to rqt_console and swri_console that doesn't depend
    on qt and can be run directly in a terminal.
  </description>

  <author email="marcalban@hatchbed.com">Marc Alban</author>
  <maintainer email="marcalban@hatchbed.com">Marc Alban</maintainer>

  <license>BSD-3-Clause</license>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>libncurses-dev</depend>
  <depend>libsystemd-dev</depend>

  <exec_depend>xclip</exec_depend>

  <export>
    <build_type>cmake</build_type>
  </export>

</package>
